---
name: 'Deploy to Prod (v5)'

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - '5.x'

env:
  DOKKU_REMOTE_URL: 'ssh://dokku@de02.api.dicebear.com:22/app'
  CDN_PULL_ZONE: 147563

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: ${{ env.DOKKU_REMOTE_URL }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Purge CDN Cache
        run: |
          curl --request POST \
            --url https://api.bunny.net/pullzone/${{ env.CDN_PULL_ZONE }}/purgeCache \
            --header 'AccessKey: ${{ secrets.CDN_ACCESS_KEY }}'